### PR TITLE
Update adkatsreputationstats.json

### PR DESCRIPTION
**Pull request by Prophet731**

### CODE REVIEW

**Comment by III-Pho3niX-III** [comment]
How to Update adkatsreputationstats.json ?

**Comment by Prophet731** [comment]
You can't update anything. This is pulled directly from github within AdKats and the BFACP. All he has to do is merge it and the warnings should subside. Getting the warnings won't break anything or change how the data works. Anything missing in the reputation stats is just skipped and is not calculated in the players actual reputation.

**Comment by ColColonCleaner** [comment]
Merged, thanks prophet.

**Comment by III-Pho3niX-III** [comment]
Thank you both for the support! :+1:

**Pull request merged**
