### PR TITLE
Added support to send reports to a Discord WebHook.

### PR DESCRIPTION
**Pull request by jbrunink**
Hi folks,

I've added support to AdKats to send player reports to a Discord WebHook. I'm having it on the testbench right now and it seems to work rather well. 

Looking for some more testers and feedback is welcome!

Thank you.

Best regards, 

Jurgen Brunink

### CODE REVIEW

**Comment by ColColonCleaner** [comment]
Looks cool. Will need to clean some things up but overall it looks well done. Thanks for following the format used in the other internal managers. I'll push it into the test branch once i resolve the conflicts there.

**Comment by ColColonCleaner** [comment]
Adding this to the test branch manually. Changes will be exactly the same as you added them to avoid causing problems.

I've added setting uploads at interval so defaults are saved.

**Comment by IamDontNoob** [comment]
From where i can got WebHoock URL?

**Comment by ColColonCleaner** [comment]
@IamDontNoob https://support.discordapp.com/hc/en-us/articles/228383668-Intro-to-Webhooks

**Pull request closed without merging**
