### PR TITLE
Update adkatsreputationstats.json

### PR DESCRIPTION
**Pull request by Prophet731**
Added missing comma

### CODE REVIEW

**Comment by Prophet731** [comment]
@ColColonCleaner 

Please merge this one asap. Reputation is broken for everyone because of a missing comma.

**Comment by ColColonCleaner** [comment]
Merged.

**Comment by III-Pho3niX-III** [comment]
Hi Prophet,

I still have these warning messages, you did a merge but i doesnt work. 
[07:07:36 12] [AdKats] WARNING: Unable to find source weight for command 123|123

**Comment by Prophet731** [comment]
Restart AdKats

**Comment by III-Pho3niX-III** [comment]
Thank you! :+1:

**Comment by windorose** [comment]
problem fixed thank you.

**Pull request merged**
